// Generates solaar-rule.yaml. The committed file must equal this script's
// output -- a test asserts it -- so the rules can never drift from the reasoning
// that produced them. Regenerate with `npm run rules`.
//
// Why a generator: the file is 128 near-identical rules whose only content is
// two numbers repeated in three places each. Hand-editing that is how a rule
// ends up testing one value and passing another, and nothing would catch it
// by eye.

const TARGET = "alebairos.mx-quick-control"
const QS = ["qs", "-p", "/usr/share/omarchy/shell", "ipc", "call", TARGET]

// The reference keyboard reports 8 levels (0-7). A device with more still
// works: its extra levels fall through to the catch-all and pay a device read,
// exactly as every level did before this file grew.
const LEVELS = 8
// Effects are a 4-bit field on BACKLIGHT2; 0-15 is the whole space.
const EFFECTS = 16

const HEADER = `# Optional: show an on-screen display when the keyboard's OWN backlight keys
# are used, and keep the panel in step with them.
#
# Why this is a separate, opt-in file rather than part of the plugin: the
# device announces backlight changes over HID++, but hearing them requires a
# process listening continuously. This plugin deliberately runs no daemon
# (constitution Principle V). Solaar already is such a process for anyone who
# runs it, and its rules engine exists precisely to react to notifications --
# so the listening is delegated to a program you were already running, rather
# than shipped as a second one.
#
# Requires Solaar to be running. Without it, nothing breaks: the panel simply
# catches up the next time you open it, as it does today.
#
# Install by appending to ~/.config/solaar/rules.yaml (create it if absent),
# then restart Solaar. After heavy use of \`solaar show\` or the plugin's own
# transport, restart Solaar again before concluding these rules are broken:
# contention can make its feature-table read for the keyboard fail, and with
# no feature table \`Feature: BACKLIGHT2\` never matches -- silently.
#
# This file is GENERATED by tests/solaar-rules.js. Edit that, not this.
#
#
# Why there is one rule per (level, effect) pair, instead of one rule
# ------------------------------------------------------------------
#
# A single \`Feature: BACKLIGHT2\` rule can only say that *something* changed,
# because Solaar's \`Execute\` action is a bare subprocess.Popen of a fixed
# argument list, with no substitution (diversion.py, class Execute). The widget
# then had to read the value back off the device: 2.0-2.3s on the reference
# hardware, most of it waking a sleeping wireless device.
#
# The values are in the notification the whole time. Captured off /dev/hidraw
# while pressing the keyboard's own keys, one frame per press:
#
#   data=0b 00 | 08 04 05 05      effect key   -> effect 5
#   data=0b 00 | 08 04 05 00      effect key   -> effect 0
#   data=0b 00 | 08 03 05 00      brightness   -> level 3
#   data=0b 00 | 08 02 05 00      brightness   -> level 2
#        ^     ^  ^  ^     ^
#        |     |  |  |     effect
#        |     |  |  level
#        |     |  level count (8 on this keyboard)
#        |     address 0x00: device-initiated, not a reply to a request
#        BACKLIGHT2 feature index on this device
#
# \`make_notification\` (base.py) hands the rule engine \`data[2:]\`, so the
# body starts at index 0: the level is at data[1] -- where Solaar's own
# handler reads it -- and the effect at data[3]. \`TestBytes: [1, 2, L, L]\`
# is "the level is L" and \`TestBytes: [3, 4, E, E]\` is "the effect is E"
# (diversion.py, range_test). Verified by evaluating the captured frames above
# through Solaar's own diversion module rather than by reading the offsets off
# a diagram.
#
# A rule that matches exactly one (level, effect) pair can pass both as
# literals. Only one rule can fire per notification -- a rule whose \`Execute\`
# runs returns None, which ends evaluation of the list (diversion.py,
# _evaluate) -- so the two values cannot be split across a level rule and an
# effect rule. Hence 8 x 16 = 128 rules, and the catch-all at the end is
# reached only when none matched.
#
# The notification is a full state report, not a delta: it does not say
# which key was pressed. The widget compares both values with what it already
# holds and shows the on-screen display for whichever moved -- brightness or
# effect -- with no device read in either case.
`

function rule(level, effect) {
  const args = [...QS, "externalState", `"${level}:${effect}"`]
  return [
    "- Rule:",
    "  - Feature: BACKLIGHT2",
    `  - TestBytes: [1, 2, ${level}, ${level}]`,
    `  - TestBytes: [3, 4, ${effect}, ${effect}]`,
    `  - Execute: [${args.join(", ")}]`,
    "",
  ].join("\n")
}

const CATCH_ALL = `# Anything the tests above did not match -- a level above ${LEVELS - 1}, an effect
# outside 0-${EFFECTS - 1}, or a device whose broadcast is shaped differently. Behaves
# as this file did before: the widget reads the device to find out what changed.
- Rule:
  - Feature: BACKLIGHT2
  - Execute: [${[...QS, "deviceChanged"].join(", ")}]
`

function pairs() {
  const out = []
  for (let level = 0; level < LEVELS; level++)
    for (let effect = 0; effect < EFFECTS; effect++) out.push([level, effect])
  return out
}

function render() {
  return HEADER + "\n%YAML 1.3\n---\n" + pairs().map(([l, e]) => rule(l, e)).join("\n") + CATCH_ALL
}

if (require.main === module) {
  process.stdout.write(render())
}

module.exports = { render, pairs, LEVELS, EFFECTS, TARGET }
